MvcNetCorePractica3/Models/ErrorViewModel.cs
namespace MvcNetCorePractica3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCorePractica3/Models/ImagenZapatos.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcNetCorePractica3.Models
{
    [Table("V_IMAGESZAPASPRACTICA")]
    public class ImagenZapatos
    {
        [Key]
        [Column("IDIMAGEN")]
        public int IdImagen { get; set; }
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
    }
}

MvcNetCorePractica3/Models/ModelPaginacionZapas.cs
namespace MvcNetCorePractica3.Models
{
    public class ModelPaginacionZapas
    {
        public List<ImagenZapatos> ImagenZapatos { get; set; }
        public Zapato zapato { get; set; }
        public int NumReigstro { get; set; }
    }
}

MvcNetCorePractica3/Models/Zapato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcNetCorePractica3.Models
{
    [Table("V_ZAPASPRACTICA")]
    public class Zapato
    {
        [Key]
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }
        [Column("PRECIO")]
        public int Precio { get; set; }
    }
}

MvcNetCorePractica3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCorePractica3.Models;
using System.Diagnostics;

namespace MvcNetCorePractica3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCorePractica3/Controllers/ZapatosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCorePractica3.Models;
using MvcNetCorePractica3.Repositories;

namespace MvcNetCorePractica3.Controllers
{
    public class ZapatosController : Controller
    {
        private RepositoryZapatos repo;
        public ZapatosController(RepositoryZapatos repo)
        {
            this.repo = repo;
        }
        public async Task<IActionResult> ZapatosIndex()
        {
            List<Zapato> zapatos = await this.repo.GetZapatosAsync();
            return View(zapatos);
        }

        public async Task<IActionResult> ZapasImagenesOut(int? posicion, int idproducto)
        {
            if (posicion == null)
            {
                posicion = 1;
            }

            ModelPaginacionZapas model = await this.repo.GetZapatosImagenes(posicion.Value, idproducto);

            int siguiente = posicion.Value + 1;

            if (siguiente > model.NumReigstro)
            {
                siguiente = model.NumReigstro;
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }
            ViewData["IDPRODUCTO"] = idproducto;
            ViewData["ZAPATILLA"] = model.zapato;
            ViewData["ULTIMO"] = model.NumReigstro;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;
            return View(model.ImagenZapatos);
        }

        public async Task<IActionResult> CrearImagenes()
        {
            List<Zapato> zapatos = await this.repo.GetZapatosAsync();
            return View(zapatos);
        }
        [HttpPost]
        public async Task<IActionResult> CrearImagenes(int idproducto, int idimagen, List<string> imagen)
        {
            this.repo.InsertImagen(imagen, idproducto, idimagen);
            return RedirectToAction("ZapatosIndex");
        }
    }
}













//if (posicion == null)
//{
//    //PONEMOS LA POSICION EN EL PRIMER REGISTRO 
//    posicion = 1;
//}
////PRIMERO = 1 
////SIGUIENTE = 
////ANTERIOR = 
////ULTIMO = 
//int numeroRegistros = await this.repo.GetNumRegistrosZapatosAsync();

//int siguiente = posicion.Value + 1;

////DEBEMOS COMPROBAR QUE NO PASAMOS DEL NUMERO DE REGISTROS 
//if (siguiente > numeroRegistros)
//{
//    //EFECTO OPTICO 
//    siguiente = numeroRegistros;
//}

//int anterior = posicion.Value - 1;

//if (anterior < 1)
//{
//    anterior = 1;
//}

//Zapato zapas = await this.repo.GetZapatosPosicionAsync(posicion.Value);

//ViewData["ULTIMO"] = numeroRegistros;

//ViewData["SIGUIENTE"] = siguiente;

//ViewData["ANTERIOR"] = anterior;

//return View(zapas);

MvcNetCorePractica3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCorePractica3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCorePractica3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCorePractica3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCorePractica3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatos" asp-action="ZapatosIndex">Zapatos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatos" asp-action="CrearImagenes">Nuevo Zapato</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcNetCorePractica3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcNetCorePractica3/Views/Zapatos/CrearImagenes.cshtml
@model List<Zapato>


<h1>Crear Imagenes Zapas</h1>

<form>
    <label>Seleccione zapato :</label>
    <select name="idproducto" class="form-control">
        @foreach (Zapato zapa in Model)
        {
            <option value="@zapa.IdProducto">@zapa.Nombre</option>
        }
    </select>
    <label>Id Imagen: </label>
    <input type="number" name="idimagen" class="form-control"/>
    <label>Introduzca imagen: </label>
    <input type="text" name="imagen" class="form-control"/>
    <button class="btn btn-info">
        Insertar
    </button>
</form>
<button id="AgregarInput">
    Agregar Input
</button>
<div id="caja">
</div>

@section Scripts {

    <script>

        $(document).ready(function () {

            $("#AgregarInput").click(function () {

                var labelNuevo = "<label>Imagen: </label>";
                var inputNuevo = "<input type='text' name='imagen' class='form-control'/>";

                $("#caja").append(labelNuevo,inputNuevo);

            })

        })

    </script>

} 

MvcNetCorePractica3/Views/Zapatos/ZapasImagenesOut.cshtml
@model List<ImagenZapatos>

@{
    Zapato zapas = ViewData["ZAPATILLA"] as Zapato;
    int registros = 0;
    int numeroPagina = 1;

    if (ViewData["REGISTROS"] != null)
    {
        registros = (int)ViewData["REGISTROS"];
    }
}

<h1>Imagenes Zapatillas</h1>

<div>
    <ul class="list-group">
        <li class="list-group-item">
            Nombre: @zapas.Nombre
        </li>
        <li class="list-group-item">
            Descripcion: @zapas.Descripcion
        </li>
        <li class="list-group-item">
            Precio: @zapas.Precio
        </li>
    </ul>
</div>


<div>
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item">
            <a asp-controller="Zapatos"
               asp-action="ZapasImagenesOut"
               asp-route-posicion="1"
               asp-route-idproducto="@ViewData["IDPRODUCTO"]">
                Primero
            </a>
        </li>
        <li class="list-group-item">
            <a asp-controller="Zapatos"
               asp-action="ZapasImagenesOut"
               asp-route-posicion="@ViewData["ANTERIOR"]"
               asp-route-idproducto="@ViewData["IDPRODUCTO"]">
                Anterior
            </a>
        </li>
        <li class="list-group-item">
            <a asp-controller="Zapatos"
               asp-action="ZapasImagenesOut"
               asp-route-posicion="@ViewData["SIGUIENTE"]"
               asp-route-idproducto="@ViewData["IDPRODUCTO"]">
                Siguiente
            </a>
        </li>
        <li class="list-group-item">
            <a asp-controller="Zapatos"
               asp-action="ZapasImagenesOut"
               asp-route-posicion="@ViewData["ULTIMO"]"
               asp-route-idproducto="@ViewData["IDPRODUCTO"]">
                Ultimo
            </a>
        </li>
    </ul>
</div>

<hr />

<h2 style="color:blue">
    Registro @ViewData["POSICION"] de @ViewData["ULTIMO"]
</h2>
@foreach (ImagenZapatos img in Model)
{
    <img src="@img.Imagen" style="width:250px;height:250px" />
}

MvcNetCorePractica3/Views/Zapatos/ZapatosIndex.cshtml
@model List<Zapato>

<h1>Lista de Zapatos</h1>

<ul class="list-group">
    @foreach (Zapato zapas in Model)
    {
        <li class="list-group-item">
            <a asp-controller="Zapatos" asp-action="ZapasImagenesOut" asp-route-idproducto="@zapas.IdProducto" class="btn btn-outline-success">@zapas.Nombre</a>
        </li>
    }
</ul>